const emoji = [
  {text: 'smile', content: '😀'},
  {text: 'laugh', content: '😂'},
  {text: 'blush', content: '😊'},
  {text: 'wink', content: '😉'},
  {text: 'heart_eyes', content: '😍'},
  {text: 'kissing_heart', content: '😘'},
  {text: 'kissing_closed_eyes', content: '😚'},
  {text: 'stuck_out_tongue_winking_eye', content: '😜'},
  {text: 'flushed', content: '😳'},
  {text: 'grin', content: '😁'},
  {text: 'pensive', content: '😔'},
  {text: 'relieved', content: '😌'},
  {text: 'unamused', content: '😒'},
  {text: 'cry', content: '😢'},
  {text: 'sob', content: '😭'},
  {text: 'sleepy', content: '😪'},
  {text: 'disappointed_relieved', content: '😥'},
  {text: 'cold_sweat', content: '😰'},
  {text: 'sweat_smile', content: '😓'},
  {text: 'scream', content: '😱'},
  {text: 'angry', content: '😠'},
  {text: 'rage', content: '😡'},
  {text: 'mask', content: '😷'},
  {text: 'face_with_sunglasses', content: '😎'},
  {text: 'sleeping', content: '😴'},
  {text: 'smirk', content: '😏'},
  {text: 'face_with_rolling_eyes', content: '🙄'},
  {text: 'thinking_face', content: '🤔'},
  {text: 'face_with_head-bandage', content: '🤕'},
  {text: 'thumbs_up', content: '👍'},
  {text: 'ok_hand', content: '👌'},
];
const def = '';
export {emoji, def};
